### ISSUE TITLE
Hakathon 115: How to run the full CDDL in CDDL diagnose which is recommended in RFC 8610

### ISSUE THREAD

**Issue by PenglinYang** [ietf-teep/teep-protocol#198] opened 2022-05-06 02:07 UTC
When I run the original full CDDL of TEEP protocol in CBOR Diagnostic tool which is recommend by the CDDL RFC8610 Appendix F, the following is the error message. 
![image](https://user-images.githubusercontent.com/80935986/167053731-ffe4005b-5767-4946-8559-8355d796133a.png)

After I delete the ".within " expression or annotate relevant sentence, the following is the result information.
![image](https://user-images.githubusercontent.com/80935986/167053325-70a95124-f039-4779-b378-13b7cf65bb30.png)

So how to run the full CDDL in CDDL diagnose, I don't know if you have tried this.

**Comment by mcd500** [comment] 2022-05-06 06:06
Hi @PenglinYang, this seems to be my expertise.
Let me work on removing the errors in the cddl.

**Comment by PenglinYang** [comment] 2022-05-06 07:05
>

**Comment by PenglinYang** [comment] 2022-05-06 07:06
> Hi @PenglinYang, this seems to be my expertise. Let me work on removing the errors in the cddl.

Thank you very much. If you need any information, I would like to help.

**Comment by mcd500** [comment] 2022-05-06 08:06
Hi @PenglinYang, do you mind teaching me which cddl command line tool you have used it?
Is it this one at the link?
https://github.com/anweiss/cddl

**Comment by PenglinYang** [comment] 2022-05-06 08:35
> Hi @PenglinYang, do you mind teaching me which cddl command line tool you have used it? Is it this one at the link? https://github.com/anweiss/cddl
No, it's https://github.com/cabo/cbor-diag, which is mentioned in https://www.rfc-editor.org/rfc/rfc8610.html#appendix-F . And the cddl spec.cddl generate [n] command of the tool is to generate examples by the "spec.cddl" document, which I use the full CDDL of TEEP protocol instead.

**Comment by mcd500** [comment] 2022-05-06 09:43
@PenglinYang thanks.
Will get back to you when I replicate your error messages.

**Comment by mcd500** [comment] 2022-05-06 12:19
@PenglinYang I was able to reproduce the exact same error with yours.
Please give me some time to fix them, about a week or so.

**Comment by mcd500** [comment] 2022-05-07 03:48
@PenglinYang Sure, thanks, definitely I will ask you.

These are the fixes I spotted so for.
```
--- draft-ietf-teep-protocol.cddl.orig	2022-05-07 12:41:54.063333960 +0900
+++ draft-ietf-teep-protocol.cddl	2022-05-06 21:15:16.177731597 +0900
@@ -24,11 +24,11 @@ TEEP-TYPE-update = 3
 TEEP-TYPE-teep-success = 5
 TEEP-TYPE-teep-error = 6
 
-version = .within uint .size 4
-ext-info = .within uint .size 4
+version = uint .size 4
+ext-info = uint .size 4
 
 ; data items as bitmaps
-data-item-requested = $data-item-requested .within uint .size 8
+data-item-requested = $data-item-requested
 attestation = 1
 $data-item-requested /= attestation
 trusted-components = 2
@@ -82,7 +82,7 @@ cose-alg-hmac-256 = 5
 
 ; freshness-mechanisms
 
-freshness-mechanism = $TEEP-freshness-mechanism .within uint .size 4
+freshness-mechanism = $TEEP-freshness-mechanism
 
 FRESHNESS_NONCE = 0
 FRESHNESS_TIMESTAMP = 1
@@ -92,6 +92,21 @@ $TEEP-freshness-mechanism /= FRESHNESS_N
 $TEEP-freshness-mechanism /= FRESHNESS_TIMESTAMP
 $TEEP-freshness-mechanism /= FRESHNESS_EPOCH_ID
 
@@ -111,12 +126,12 @@ query-response = [
 
 tc-info = {
   component-id => SUIT_Component_Identifier,
-  ? tc-manifest-sequence-number => .within uint .size 8
+  ? tc-manifest-sequence-number => uint .size 8
 }
 
 requested-tc-info = {
   component-id => SUIT_Component_Identifier,
-  ? tc-manifest-sequence-number => .within uint .size 8
+  ? tc-manifest-sequence-number => uint .size 8
   ? have-binary => bool
 }
 
@@ -135,7 +150,7 @@ teep-success = [
   options: {
     ? token => bstr .size (8..64),
     ? msg => text .size (1..128),
-    ? suit-reports => [ + suit-report ],
+    ? suit-reports => [ + SUIT_Report ],
     * $$teep-success-extensions,
     * $$teep-option-extensions
   }
@@ -149,7 +164,7 @@ teep-error = [
      ? supported-cipher-suites => [ + ciphersuite ],
      ? supported-freshness-mechanisms => [ + freshness-mechanism ],
      ? versions => [ + version ],
-     ? suit-reports => [ + suit-report ],
+     ? suit-reports => [ + SUIT_Report ],
      * $$teep-error-extensions,
      * $$teep-option-extensions
   },
```

I have to continue with some of the CDDL definition from SUIT to continue.

From end of April to the first week of May is a holiday week here and just my feeling is not enough for pursuing to finishing debugging. :)
Let me continue them when regular office week day starting from Monday.

**Comment by mcd500** [comment] 2022-05-10 06:22
Hi @PenglinYang, this is what I have done so far.
I realized that cddl embedded in the markdown file require splitting the cddl file manually from .md file, so made the PR for it.
https://github.com/ietf-teep/teep-protocol/pull/200

And then made some fixes for the cddl syntax errors.
https://github.com/ietf-teep/teep-protocol/pull/201

**Comment by mcd500** [comment] 2022-05-10 06:35
For running cddl tool, I will be writing entire procedure so others could repeat it too.
First I installed cddl tool on my ubuntu machine.
```
sudo gem install cddl
```
I downloaded the cddl files which depended with the teep protocol.
The cddl for the suit-manifest from bellow. 
https://github.com/suit-wg/manifest-spec/blob/master/draft-ietf-suit-manifest.cddl
And then created the suit-report.cddl file for SUIT_Report manually from:
https://www.ietf.org/archive/id/draft-ietf-suit-report-01.html

Then concatenated them with:
```
cat suit-manifest-ietf.cddl suit-report.cddl draft-ietf-teep-protocol.cddl > check-draft-ietf-teep-protocol.cddl
```
and executed cddl file as follow.
```
cddl check-draft-ietf-teep-protocol.cddl generate
```
Getting the result as:
```
*** snipped ***
*** Unused rule suit-reports
*** Unused rule token
*** Unused rule supported-freshness-mechanisms
107({2: h'844F82382C4B6D69736265676F7474656E4111421862421862', 3: h'A4010102190959035828A2028184446265656E47706164646965734661736863616E49636F6E74726976656404448218180F0C4886160F050F181F0F', 8: h'86030F0E0F170F', 13: h'A3016674726F696B61834A4E657373656C726F64654873706174746572734B506C61746F6E69736D2773A6016B636F6F706572617469766502656C75636B730367626163696C6C6904676261736B696E67056561726F6D61066876657269747927738449696E73706972696E674F746F72746F6973657368656C6C27734657656265726E4467656564A20166646F7A656E730566726564726577'})
```

Probably it require reordering cddl for generating cddl for particular teep message.
I am also not sure how to try the full CDDL in CDDL diagnose than what I tried above.

It may still need additional expression in cddl portion in teep draft to make it complete.

**Comment by mcd500** [comment] 2022-05-10 10:12
Forgot to add one thing.

I added one line bellow before trying the cddl tool to the suit-manifest-ietf.cddl from referring https://www.ietf.org/archive/id/draft-ietf-suit-trust-domains-00.html

```
suit-directive-process-dependency       = 18
```

**Comment by mcd500** [comment] 2022-05-11 08:55
@PenglinYang Thanks for trying.
For the
```
COSE_Mac_Tagged = 97 COSE_Mac0_Tagged = 17 COSE_Sign_Tagged = 98 COSE_Sign1_Tagged = 18 
```
they were added to cddl with this PR a short while ago.
https://github.com/ietf-teep/teep-protocol/pull/194

After the this PR https://github.com/ietf-teep/teep-protocol/pull/201 being merged, it should be showing the similar result with yours.

I will start seeking experts on obtaining how to make the TEEP full CDDL work with cddl tools.

**Comment by dthaler** [comment] 2022-07-08 12:55
@mcd500 any progress?

**Comment by kentakayama** [comment] 2022-08-30 12:17
@PenglinYang @mcd500 @dthaler 
I wish the PR #248 and #249 fix this issue.

**Comment by mcd500** [comment] 2023-03-24 02:33
How to run cddl tool to check cddl syntax was added to the readme in the section "Run cddl tools" during the hacakthon 115.
Closing it.

**Closed by mcd500** 2023-03-24 02:33 UTC
Labels: ready to close
